# Generated by Django 4.2.11 on 2024-04-19 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_sessioninvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioninvite',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_invite_receiver', to='profiles.profile'),
        ),
    ]
