# Generated by Django 4.2.11 on 2024-04-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_sessioninvite_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioninvite',
            name='inbound',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='profiles.profile'),
        ),
    ]
