# Generated by Django 4.2.11 on 2024-04-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_author_group_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='private_group',
            new_name='private',
        ),
    ]
